# -------------------------------------
# GitHub Action - Evgenii Sviridov 2023
# -------------------------------------

name: My-GitHubActions-Basics
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME: "Flask-Deploy-Ver-${{ github.sha }}"

on: 
  push:
    branches: 
      - main

jobs:
  my-testing:  
    runs-on: Ubuntu-Latest

    steps:
      - name: Git Clone my repo
        uses: actions/checkout@v1
        
      - name: Print Hello Message
        run: echo "Hello World from Testing job"
        
      - name: Execute few commands
        run: |
          echo "Hello Message 1"
          echo "Hello Message 2"
          echo "Application name:${{ env.APPLICATION_NAME }}"

      - name: list Current Folder
        run: ls -la


  my-deploy:  
    runs-on: Ubuntu-Latest
    needs: [my-testing]
    env:
      VAR1: "This is Job Level Variable1"
      VAR2: "This is Job Level Variable2"
      
    steps:
      - name: Git Clone my repo
        uses: actions/checkout@v1
        
      - name: Print Hello Message
        run: echo "Hello World from Deploy job"

      - name: Print env vars
        run: |
          echo "Var1 = ${{ env.VAR1 }}"
          echo "Var2 = ${{ env.VAR2 }}"
          echo "Var3 = $LOCAL_VAR"
        env:
          LOCAL_VAR: "This is Local Variable"

          
      - name: Printing Deployment Package
        run: echo "Deploy package name is:${{ env.DEPLOY_PACKAGE_NAME }}"
         
      - name: Lets Test some Package AWS
        run: aws --version
         
      - name: Lets Test some Package ZIP
        run: zip --version
