# -------------------------------------
# GitHub Action - Evgenii Sviridov 2023
# -------------------------------------

name: CICD-Pipeline-to-AWS-Elastic-Beanstalk

env:
  EB_PACKAGE_S3_BUCKET_NAME: "evgeniyisv.flask.app.package"
  EB_APPLICATION_NAME: "MyFlask"
  EB_ENVIRONMENT_NAME: "MyFlask-env"
  DEPLOYMENT_PACKAGE_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-central-1"
  
on: 
  push:
    branches: 
      - main

jobs:
  my-CI-part:  
    runs-on: Ubuntu-Latest

    steps:
      - name: Git Clone my repo
        uses: actions/checkout@v1
        
      - name: Create ZIP Deployment package
        run: zip -r ${{ env.DEPLOYMENT_PACKAGE_NAME }} ./ -x *.git*
        
      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secret.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secret.MY_AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
                
      - name: Copy Deployment to S3 bucket
        run: aws s3 cp ${{ env.DEPLOYMENT_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}
        
      - name: Print Happy Message for CI Finish
        run: echo "CI PipeLine part 2 Finished!"
