# -------------------------------------
# GitHub Action - Evgenii Sviridov 2023
# -------------------------------------

name: CICD-Pipeline-to-AWS-Elastic-Beanstalk

env:
  EB_PACKAGE_S3_BUCKET_NAME: "evgeniyisv.flask.app.package"
  EB_APPLICATION_NAME: "MyFlask"
  EB_ENVIRONMENT_NAME: "MyFlask-env"
  DEPLOYMENT_PACKAGE_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-central-1"
  
on: 
  push:
    branches: 
      - main

jobs:
  my-CI-part:  
    runs-on: Ubuntu-Latest

    steps:
      - name: Git Clone my repo
        uses: actions/checkout@v1
        
      - name: Create ZIP Deployment package
        run: zip -r ${{ env.DEPLOYMENT_PACKAGE_NAME }} ./ -X *.git*
